### PR TITLE
fix: support build on 32-bit int environments

### PR DESCRIPTION
**Pull request by orisano**
Since https://github.com/cosnicolaou/pbzip2/pull/42
Fix build errors on platforms where int is 32-bit

### CODE REVIEW

**Review by klauspost — APPROVED** [review]
lgtm

**Comment by klauspost** [comment]
For my packages I do a `GOARCH=386 go test -short ./...` - this should test if it builds and runs on 32 bit. consider adding that to CI as a regression test.

**Comment by orisano** [comment]
@cosnicolaou I'm looking forward to version 1.0.5!

**Comment by cosnicolaou** [comment]
Sorry, I created 1.04 two weeks ago but forgot to tag it as the latest
release, it should appear on the home page now.

**Comment by cosnicolaou** [comment]
and I just create 1.0.5 to capture the 32 bit support.

**Pull request merged**
