### PR TITLE
update CI to use github actions and fix long-standing race condition on error 

### PR DESCRIPTION
**Pull request by cosnicolaou**

### CODE REVIEW

**Comment by klauspost** [comment]
Usually I use the `testing.Short()` for race runs, and use a lighter load for those. Maybe that would make sense here?

**Comment by cosnicolaou** [comment]
Oh, the problem is not a slow test but a deadlock. I’m not sure uet why it
surfaced now, but goroutine scheduling is sufficiently different on Mac and
Linux for the bug to surface on Linux.

**Comment by cosnicolaou** [comment]
Sorry, I meant to ask you, are you ok with my bumping this up to go 1.18 or
later?

Cheers, Cos.

**Comment by klauspost** [comment]
@cosnicolaou I personally only support the last 3 versions in my packages - and I wouldn't expect any package to support more than Go does. So 1.18 would be very fine by me.

**Comment by cosnicolaou** [comment]
Ok, l will take care of that and bump the release later today.

Cheers, Cos.

**Pull request merged**
